version: '3.8'

services:
  tpr-generator:
    image: tpr-generator:${IMAGE_VERSION}
    ports:
      - '${HOST_PORT:-3000}:3500'
    volumes:
      - tpr-generator-data:${TPRGEN_VOLUME_ROOT}
    configs:
      - env_config
    secrets:
      - jwt_secret
      - seedhash_secret

volumes:
  tpr-generator-data:
    driver: local

configs:
  env_config:
    file: ./.env
    name: env_config-${ENV_CONFIG_HASH}

secrets:
  jwt_secret:
    file: ./secrets/jwtSecret.txt
    name: jwt_secret-${JWT_SECRET_HASH}
  seedhash_secret:
    file: ./secrets/seedHashSecret.txt
    name: seedhash_secret-${SEEDHASH_SECRET_HASH}
