namespace TPRandomizer
{
    using System.Collections.Generic;

    /// <summary>
    /// summary text.
    /// </summary>
    public class HashAssets
    {
        /// <summary>
        /// summary text.
        /// </summary>
        public static List<string> characterNames = new List<string>()
        {
            "Link",
            "Wolf Link",
            "Midna",
            "Zant",
            "Zelda",
            "Ganondorf",
            "Agitha",
            "Ashei",
            "Auru",
            "Barnes",
            "Beth",
            "Colin",
            "Coro",
            "Dangoro",
            "Darbus",
            "Borville",
            "Eldin",
            "Fado",
            "Falbi",
            "Faron",
            "Fyer",
            "Gor Amoto",
            "Gor Coron",
            "Gor Ebizo",
            "Gor Liggs",
            "Great Fairy",
            "Hanch",
            "Hena",
            "Ilia",
            "Impaz",
            "Iza",
            "Jaggle",
            "Jovani",
            "King Bulblin",
            "Lanayru",
            "Luda",
            "Malo",
            "Bo",
            "Ooccoo",
            "Ooccoo Jr.",
            "Ordona",
            "Postman",
            "Purlo",
            "Ralis",
            "Rutela",
            "Renado",
            "Rusl",
            "Sera",
            "Shad",
            "Skull Kid",
            "Talo",
            "Telma",
            "Uli",
            "Yeta",
            "Yeto",
            "Epona",
            "Gengle",
            "Lord Bullbo",
            "Louise",
            "Ook",
            "Plumm",
            "Purdy",
            "Trill",
            "Charlo",
            "Chudley",
            "Fanadi",
            "Hannah",
            "Kili",
            "Malver",
            "Misha",
            "Pergie",
            "Soal",
            "Dangoro",
            "Deku Toad",
            "Death Sword",
            "Darkhammer",
            "Darknut",
            "Aeralfos",
        };

        /// <summary>
        /// summary text.
        /// </summary>
        public static List<string> hashAdjectives = new List<string>()
        {
            "Anxious",
            "Naughty",
            "Stubborn",
            "Sensitive",
            "Intelligent",
            "Nice",
            "Emotional",
            "Bad-tempered",
            "Nervous",
            "Mean",
            "Distracted",
            "Dishonest",
            "Rude",
            "Discreet",
            "Crazy",
            "Cheeky",
            "Cheerful",
            "Energetic",
            "Untidy",
            "Pessimistic",
            "Optimistic",
            "Unpleasant",
            "Talkative",
            "Calm",
            "Passionate",
            "Proud",
            "Sincere",
            "Lazy",
            "Lively",
            "Funny",
            "Silly",
            "Shy",
            "Determined",
            "Versatile",
            "Sociable",
            "Worried",
            "Thoughtful",
            "Humble",
            "Friendly",
            "Frank",
            "Obedient",
            "Honest",
            "Fearless",
            "Unfriendly",
            "Generous",
            "Compassionate",
            "Warm-hearted",
            "Disobedient",
            "Straightforward",
            "Selfish",
            "Imaginative",
            "Placid",
            "Jealous",
            "Helpful",
            "Enthusiastic",
            "Persistent",
            "Sensible",
            "Rational",
            "Reserved",
            "Self-confident",
            "Bossy",
            "Plucky",
            "Patient",
            "Impatient",
            "Easygoing",
            "Careless",
            "Messy",
            "Hard-working",
            "Creative",
            "Broad-minded",
            "Faithful",
            "Kind",
            "Courageous",
            "Loyal",
            "Modest",
            "Tidy",
            "Confident",
            "Attentive",
            "Loving",
            "Reliable",
            "Scared",
            "Conscientious",
            "Good-tempered",
            "Careful",
            "Gentle",
            "Neat",
            "Dynamic",
            "Fair-minded",
            "Impartial",
            "Supportive",
            "Timid",
            "Intellectual",
            "Brave",
            "Ambitious",
            "Polite",
            "Happy",
            "Romantic",
            "Diplomatic",
            "Courteous",
            "Humorous",
            "Self-disciplined",
            "Popular",
            "Smart",
            "Serious",
            "Hypocritical",
            "Adventurous",
        };
    }
}
